### ISSUE TITLE
Abort shutdown isn’t working

### ISSUE THREAD

**Issue by CTRLDON** [francofgp/shutty-a-shutdown-timer#1]
I tested this app (.py version ) on ubuntu.
I sat a time then aborted it , but it didn't

**Comment by francofgp** [comment]
I think the problem is that, I use this library [Shutdow](https://github.com/sepandhaghighi/pyshutdown), and this library already have this issue [Issue Unix not working](https://github.com/sepandhaghighi/pyshutdown/issues/2), so it only works on Windows.

Could you pelase tell me if you can turn off the computare properly with the app?

**Comment by CTRLDON** [comment]
> I think the problem is that, I use this library [Shutdow](https://github.com/sepandhaghighi/pyshutdown), and this library already have this issue [Issue Unix not working](https://github.com/sepandhaghighi/pyshutdown/issues/2), so it only works on Windows.
> 
> 
> 
> Could you pelase tell me if you can turn off the computare properly with the app?

Yeah the app is working but only the abort button isn't working I checked shutdown library code and i think i found a solution maybe i could fix it.
